# Generated by Django 2.2 on 2019-08-14 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_coursetag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='learn_times',
        ),
        migrations.AddField(
            model_name='courses',
            name='notice',
            field=models.CharField(default='', max_length=100, verbose_name='课程公告'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lessons', verbose_name='课程章节'),
        ),
    ]
