# Generated by Django 2.2 on 2019-08-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190815_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否轮播图'),
        ),
    ]
