# Generated by Django 2.2 on 2019-08-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_basemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='head_image/default.jpg', upload_to='head_image/%Y/%m', verbose_name='用户头像'),
        ),
    ]
