# Generated by Django 2.2 on 2019-08-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='城市名'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='机构名称'),
        ),
    ]
