# Generated by Django 2.2 on 2019-08-08 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20190807_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Cities', verbose_name='城市'),
        ),
    ]
