# Generated by Django 2.2 on 2019-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20190808_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='org/images/%Y/%m', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='image',
            field=models.ImageField(upload_to='teacher/images/%Y/%m', verbose_name='头像'),
        ),
    ]
