# Generated by Django 2.2 on 2019-08-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20190811_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='has_auth',
            field=models.BooleanField(default=False, verbose_name='是否认证'),
        ),
    ]
