# Generated by Django 2.2 on 2019-08-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_teachers_has_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='has_auth',
            new_name='is_auth',
        ),
        migrations.AddField(
            model_name='teachers',
            name='is_gold',
            field=models.BooleanField(default=False, verbose_name='是否金牌'),
        ),
    ]
